// <auto-generated />
using ClassLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PlatformDemoWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Name = "Alice",
                            PhoneNumber = "09202535208"
                        },
                        new
                        {
                            CustomerId = 2,
                            Name = "Bob",
                            PhoneNumber = "09857360608"
                        },
                        new
                        {
                            CustomerId = 3,
                            Name = "Charlie",
                            PhoneNumber = "09666813985"
                        },
                        new
                        {
                            CustomerId = 4,
                            Name = "David",
                            PhoneNumber = "09669788047"
                        },
                        new
                        {
                            CustomerId = 5,
                            Name = "Ella",
                            PhoneNumber = "09262812603"
                        },
                        new
                        {
                            CustomerId = 6,
                            Name = "Frank",
                            PhoneNumber = "09401388259"
                        },
                        new
                        {
                            CustomerId = 7,
                            Name = "Grace",
                            PhoneNumber = "09705412539"
                        },
                        new
                        {
                            CustomerId = 8,
                            Name = "Hannah",
                            PhoneNumber = "09205729248"
                        },
                        new
                        {
                            CustomerId = 9,
                            Name = "Isaac",
                            PhoneNumber = "09321675762"
                        },
                        new
                        {
                            CustomerId = 10,
                            Name = "Julia",
                            PhoneNumber = "09922937263"
                        },
                        new
                        {
                            CustomerId = 11,
                            Name = "Karl",
                            PhoneNumber = "09455051349"
                        },
                        new
                        {
                            CustomerId = 12,
                            Name = "Lily",
                            PhoneNumber = "09271307752"
                        },
                        new
                        {
                            CustomerId = 13,
                            Name = "Michael",
                            PhoneNumber = "09469726943"
                        },
                        new
                        {
                            CustomerId = 14,
                            Name = "Nora",
                            PhoneNumber = "09913819504"
                        },
                        new
                        {
                            CustomerId = 15,
                            Name = "Oliver",
                            PhoneNumber = "09283295962"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Entities.Customer", b =>
                {
                    b.OwnsMany("ClassLibrary.Entities.Order", "Orders", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("OrderId"));

                            b1.Property<double>("Amount")
                                .HasColumnType("float");

                            b1.Property<int>("CustomerId")
                                .HasColumnType("int");

                            b1.Property<string>("OrderNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderId");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("Order");

                            b1.WithOwner("Customer")
                                .HasForeignKey("CustomerId");

                            b1.Navigation("Customer");

                            b1.HasData(
                                new
                                {
                                    OrderId = 521,
                                    Amount = 318027.0,
                                    CustomerId = 2,
                                    OrderNumber = "2bb497f4-d8db-41ea-b6e7-cbb1a7222a14"
                                },
                                new
                                {
                                    OrderId = 28,
                                    Amount = 423557.0,
                                    CustomerId = 3,
                                    OrderNumber = "e7237389-4923-45db-b915-a725bf1e8a15"
                                },
                                new
                                {
                                    OrderId = 738,
                                    Amount = 372193.0,
                                    CustomerId = 3,
                                    OrderNumber = "6aa10a30-9614-4ca6-9de4-f5352f7ff210"
                                },
                                new
                                {
                                    OrderId = 586,
                                    Amount = 169921.0,
                                    CustomerId = 3,
                                    OrderNumber = "21bc3a9d-db29-4fa4-808c-8ca440283af4"
                                },
                                new
                                {
                                    OrderId = 575,
                                    Amount = 232072.0,
                                    CustomerId = 3,
                                    OrderNumber = "fe37a7a5-3f3f-44cf-a048-d4786e0fb1f3"
                                },
                                new
                                {
                                    OrderId = 85,
                                    Amount = 367006.0,
                                    CustomerId = 4,
                                    OrderNumber = "95b9a2c3-8479-4254-ac11-3b2aa98e67d3"
                                },
                                new
                                {
                                    OrderId = 345,
                                    Amount = 122025.0,
                                    CustomerId = 4,
                                    OrderNumber = "6e576388-1b08-4ca9-89ec-7f1475225fbb"
                                },
                                new
                                {
                                    OrderId = 784,
                                    Amount = 112854.0,
                                    CustomerId = 4,
                                    OrderNumber = "db2701d3-e46b-4b54-888d-1c530eeccb62"
                                },
                                new
                                {
                                    OrderId = 709,
                                    Amount = 309174.0,
                                    CustomerId = 5,
                                    OrderNumber = "844e85c4-45d4-425c-bac0-b14f68e411e6"
                                },
                                new
                                {
                                    OrderId = 661,
                                    Amount = 310415.0,
                                    CustomerId = 5,
                                    OrderNumber = "adb1ea73-d485-41cf-a6ae-5d87dc3777cd"
                                },
                                new
                                {
                                    OrderId = 33,
                                    Amount = 176577.0,
                                    CustomerId = 6,
                                    OrderNumber = "582efbf7-031a-478d-ae0c-b359e146c16f"
                                },
                                new
                                {
                                    OrderId = 885,
                                    Amount = 95663.0,
                                    CustomerId = 6,
                                    OrderNumber = "61468e1f-9d4b-417a-8b1f-3e9d5a427b97"
                                },
                                new
                                {
                                    OrderId = 326,
                                    Amount = 424462.0,
                                    CustomerId = 6,
                                    OrderNumber = "be28efe7-5654-42e7-9e30-79f5c741b789"
                                },
                                new
                                {
                                    OrderId = 683,
                                    Amount = 490513.0,
                                    CustomerId = 7,
                                    OrderNumber = "60a987af-f32a-4619-98e7-e5ad9ccd874f"
                                },
                                new
                                {
                                    OrderId = 282,
                                    Amount = 267673.0,
                                    CustomerId = 8,
                                    OrderNumber = "732777d3-01d3-42c9-9148-cb116aaa9dc0"
                                },
                                new
                                {
                                    OrderId = 256,
                                    Amount = 487206.0,
                                    CustomerId = 8,
                                    OrderNumber = "cb620be4-a92b-4289-80ab-8f216f6c69f3"
                                },
                                new
                                {
                                    OrderId = 243,
                                    Amount = 92975.0,
                                    CustomerId = 10,
                                    OrderNumber = "6a6ff05a-4b83-4841-a042-0962d5850517"
                                },
                                new
                                {
                                    OrderId = 446,
                                    Amount = 468012.0,
                                    CustomerId = 10,
                                    OrderNumber = "1bae75c5-cbe7-4667-8273-5dbe477907eb"
                                },
                                new
                                {
                                    OrderId = 676,
                                    Amount = 123262.0,
                                    CustomerId = 10,
                                    OrderNumber = "ade4ba23-1962-4833-83b4-a75d892bb5a7"
                                },
                                new
                                {
                                    OrderId = 608,
                                    Amount = 232560.0,
                                    CustomerId = 10,
                                    OrderNumber = "072311bc-4145-4ab3-b20b-08d18b32b370"
                                },
                                new
                                {
                                    OrderId = 737,
                                    Amount = 168254.0,
                                    CustomerId = 11,
                                    OrderNumber = "6878489b-4b2e-40ad-974b-f2a2a28a2dc9"
                                },
                                new
                                {
                                    OrderId = 259,
                                    Amount = 447155.0,
                                    CustomerId = 11,
                                    OrderNumber = "ecab4b47-dccd-4cac-ba55-494b29724900"
                                },
                                new
                                {
                                    OrderId = 630,
                                    Amount = 190705.0,
                                    CustomerId = 11,
                                    OrderNumber = "1b25f9cd-5125-4ea5-80f7-e53734bb9602"
                                },
                                new
                                {
                                    OrderId = 639,
                                    Amount = 195919.0,
                                    CustomerId = 12,
                                    OrderNumber = "305a1d14-a2b4-45aa-bc34-730fd18fc264"
                                },
                                new
                                {
                                    OrderId = 480,
                                    Amount = 83431.0,
                                    CustomerId = 12,
                                    OrderNumber = "22558757-e726-4438-96c4-924a7142f531"
                                },
                                new
                                {
                                    OrderId = 336,
                                    Amount = 135573.0,
                                    CustomerId = 12,
                                    OrderNumber = "074725c3-a0b1-49f3-84b8-53cb245a5fa8"
                                },
                                new
                                {
                                    OrderId = 607,
                                    Amount = 402410.0,
                                    CustomerId = 12,
                                    OrderNumber = "99b71fc2-dbdd-451c-989a-dda8095d3edd"
                                },
                                new
                                {
                                    OrderId = 321,
                                    Amount = 264037.0,
                                    CustomerId = 13,
                                    OrderNumber = "c4779e9c-8674-4da2-95a2-59089d4b9a6a"
                                },
                                new
                                {
                                    OrderId = 593,
                                    Amount = 109045.0,
                                    CustomerId = 13,
                                    OrderNumber = "d815a439-60fe-40ce-9366-f5e62b01b5ed"
                                },
                                new
                                {
                                    OrderId = 632,
                                    Amount = 496812.0,
                                    CustomerId = 13,
                                    OrderNumber = "55416328-0054-4c72-8b23-fa8a4a90d1eb"
                                },
                                new
                                {
                                    OrderId = 611,
                                    Amount = 95860.0,
                                    CustomerId = 13,
                                    OrderNumber = "d3136d04-bfe4-457c-9421-90525026d0ad"
                                },
                                new
                                {
                                    OrderId = 304,
                                    Amount = 431966.0,
                                    CustomerId = 14,
                                    OrderNumber = "53bb440f-a697-4643-8af7-9619869d0454"
                                },
                                new
                                {
                                    OrderId = 453,
                                    Amount = 370433.0,
                                    CustomerId = 14,
                                    OrderNumber = "251dc470-ddf6-41a2-9034-bccc0a1b7291"
                                },
                                new
                                {
                                    OrderId = 494,
                                    Amount = 375391.0,
                                    CustomerId = 14,
                                    OrderNumber = "f4eb081d-d953-4ba2-b106-7a0235fc0ad5"
                                },
                                new
                                {
                                    OrderId = 254,
                                    Amount = 417594.0,
                                    CustomerId = 15,
                                    OrderNumber = "996cd705-11a0-4cdc-9217-0da004cd615f"
                                },
                                new
                                {
                                    OrderId = 663,
                                    Amount = 43423.0,
                                    CustomerId = 15,
                                    OrderNumber = "d682d744-e4e7-4fe1-873b-42a07388fec3"
                                },
                                new
                                {
                                    OrderId = 440,
                                    Amount = 276142.0,
                                    CustomerId = 15,
                                    OrderNumber = "cb23a98c-5c39-4392-8253-a4fd5aa739d8"
                                });
                        });

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
